# Generated by Django 4.2.7 on 2025-10-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FaceRecognitionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="用户名"
                    ),
                ),
                (
                    "is_real_person",
                    models.BooleanField(default=False, verbose_name="是否真人"),
                ),
                ("status", models.CharField(max_length=20, verbose_name="状态")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="识别时间"),
                ),
            ],
            options={
                "verbose_name": "人脸识别日志",
                "verbose_name_plural": "人脸识别日志",
                "db_table": "face_recognition_log",
                "ordering": ["-created_at"],
            },
        ),
    ]
