# Generated by Django 4.2.7 on 2025-10-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "name",
                    models.CharField(
                        db_column="Name",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("password", models.CharField(db_column="Password", max_length=255)),
            ],
            options={
                "db_table": "admin",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Enterprise",
            fields=[
                (
                    "eid",
                    models.CharField(
                        db_column="EID",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_column="Name", max_length=100)),
            ],
            options={
                "db_table": "Enterprise",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Manager",
            fields=[
                (
                    "name",
                    models.CharField(
                        db_column="Name",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("password", models.CharField(db_column="Password", max_length=255)),
                ("rep", models.CharField(db_column="Rep", max_length=255, null=True)),
                ("eid", models.CharField(db_column="EID", max_length=50, null=True)),
            ],
            options={
                "db_table": "manager",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SecurityProblem",
            fields=[
                (
                    "name",
                    models.CharField(
                        db_column="Name",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "problem1",
                    models.CharField(db_column="Problem1", max_length=255, null=True),
                ),
                (
                    "answer1",
                    models.CharField(db_column="Answer1", max_length=255, null=True),
                ),
                (
                    "problem2",
                    models.CharField(db_column="Problem2", max_length=255, null=True),
                ),
                (
                    "answer2",
                    models.CharField(db_column="Answer2", max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "Security_Problem",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Verification",
            fields=[
                (
                    "name",
                    models.CharField(
                        db_column="Name",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(db_column="Email", max_length=100, unique=True),
                ),
            ],
            options={
                "db_table": "verification",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Visitor",
            fields=[
                (
                    "name",
                    models.CharField(
                        db_column="Name",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("password", models.CharField(db_column="Password", max_length=255)),
            ],
            options={
                "db_table": "visitor",
                "managed": False,
            },
        ),
    ]
