# Generated by Django 4.2.23 on 2025-08-16 04:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="配置键"
                    ),
                ),
                ("value", models.TextField(verbose_name="配置值")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "系统配置",
                "verbose_name_plural": "系统配置",
                "db_table": "system_config",
            },
        ),
        migrations.CreateModel(
            name="ViolationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "camera_id",
                    models.CharField(
                        choices=[
                            ("cam_11", "CAM_11"),
                            ("cam_28", "CAM_28"),
                            ("cam_34", "CAM_34"),
                            ("D11", "D11"),
                            ("D28", "D28"),
                            ("D34", "D34"),
                        ],
                        max_length=50,
                        verbose_name="摄像头ID",
                    ),
                ),
                ("detection_timestamp", models.DateTimeField(verbose_name="检测时间")),
                ("violation_data", models.JSONField(verbose_name="违规数据")),
                (
                    "image_path",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="图片路径"
                    ),
                ),
                (
                    "total_violations",
                    models.IntegerField(default=0, verbose_name="总违规次数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "违规记录",
                "verbose_name_plural": "违规记录",
                "db_table": "violations_records",
                "ordering": ["-detection_timestamp"],
                "indexes": [
                    models.Index(
                        fields=["camera_id", "detection_timestamp"],
                        name="violations__camera__9a903f_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="violations__created_e7a4be_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AIQueryHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.TextField(verbose_name="查询内容")),
                (
                    "time_range_hours",
                    models.IntegerField(default=24, verbose_name="时间范围(小时)"),
                ),
                (
                    "query_all_data",
                    models.BooleanField(default=False, verbose_name="查询所有数据"),
                ),
                ("response_data", models.JSONField(verbose_name="响应数据")),
                ("success", models.BooleanField(default=True, verbose_name="是否成功")),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "processing_time",
                    models.FloatField(default=0.0, verbose_name="处理时间(秒)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI查询历史",
                "verbose_name_plural": "AI查询历史",
                "db_table": "ai_query_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIAnalysisReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analysis_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="分析ID"
                    ),
                ),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[
                            ("janus_model", "Janus模型"),
                            ("rule_engine", "规则引擎"),
                            ("multimodal_simulation", "多模态模拟"),
                            ("comprehensive", "综合分析"),
                            ("quick", "快速分析"),
                            ("risk_focused", "风险关注"),
                            ("compliance", "合规分析"),
                            ("error", "错误分析"),
                        ],
                        default="rule_engine",
                        max_length=50,
                        verbose_name="分析类型",
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("无风险", "无风险"),
                            ("低风险", "低风险"),
                            ("中风险", "中风险"),
                            ("高风险", "高风险"),
                            ("未知", "未知"),
                        ],
                        default="低风险",
                        max_length=20,
                        verbose_name="风险等级",
                    ),
                ),
                ("analysis_result", models.JSONField(verbose_name="分析结果")),
                ("summary", models.TextField(blank=True, verbose_name="摘要")),
                (
                    "recommendations",
                    models.JSONField(default=list, verbose_name="建议"),
                ),
                (
                    "compliance_score",
                    models.IntegerField(default=0, verbose_name="合规分数"),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.8,
                        max_digits=3,
                        verbose_name="置信度分数",
                    ),
                ),
                (
                    "processing_time",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="处理时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "violation_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="monitor.violationrecord",
                        verbose_name="关联违规记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI分析报告",
                "verbose_name_plural": "AI分析报告",
                "db_table": "ai_analysis_reports",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["analysis_id"], name="ai_analysis_analysi_101b08_idx"
                    ),
                    models.Index(
                        fields=["risk_level"], name="ai_analysis_risk_le_d6e7a4_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="ai_analysis_created_2f798d_idx"
                    ),
                ],
            },
        ),
    ]
