# Generated by Django 4.2.23 on 2025-08-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0002_add_image_path_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="violationrecord",
            name="image_path",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="图片路径"
            ),
        ),
    ]
