# Generated by Django 4.2.7 on 2025-10-05 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0003_alter_violationrecord_image_path"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceWarehouse",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200, verbose_name="仓库名称")),
                ("eid", models.CharField(max_length=50, verbose_name="企业EID")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "设备仓库",
                "verbose_name_plural": "设备仓库",
                "db_table": "device_warehouses",
            },
        ),
        migrations.CreateModel(
            name="ManagerPeer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("manager_name", models.CharField(max_length=100)),
                ("eid", models.CharField(max_length=50)),
                ("peer_id", models.CharField(blank=True, max_length=255)),
                ("signal_endpoint", models.CharField(blank=True, max_length=255)),
                ("last_heartbeat", models.DateTimeField(null=True)),
                ("is_online", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "manager_peers",
                "unique_together": {("manager_name", "eid")},
            },
        ),
        migrations.CreateModel(
            name="WarehouseFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255, verbose_name="文件名")),
                (
                    "file_path",
                    models.CharField(max_length=500, verbose_name="文件路径"),
                ),
                ("upload_date", models.DateField(verbose_name="上传日期")),
                ("eid", models.CharField(max_length=50, verbose_name="关联EID")),
                ("file_size", models.BigIntegerField(verbose_name="文件大小")),
                (
                    "status",
                    models.CharField(
                        default="uploaded", max_length=20, verbose_name="状态"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="monitor.devicewarehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "仓库文件",
                "verbose_name_plural": "仓库文件",
                "db_table": "warehouse_files",
                "indexes": [
                    models.Index(
                        fields=["eid", "upload_date"], name="warehouse_f_eid_ac8c5e_idx"
                    )
                ],
            },
        ),
    ]
