# Generated by Django 4.2.27 on 2026-01-15 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_devicewarehouse_managerpeer_warehousefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicewarehouse',
            name='warehouse_type',
            field=models.CharField(choices=[('json', 'JSON数据'), ('mp4', 'MP4视频')], default='json', max_length=10, verbose_name='仓库类型'),
        ),
        migrations.AddField(
            model_name='warehousefile',
            name='file_type',
            field=models.CharField(default='json', max_length=50, verbose_name='文件类型'),
        ),
    ]
