# Generated by Django 4.2.20 on 2025-08-16 04:28

import detection.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('source_type', models.CharField(choices=[('camera', 'USB/Built-in Camera'), ('rtsp', 'RTSP Stream'), ('file', 'Video File')], max_length=10)),
                ('source_url', models.CharField(help_text='Camera index (0, 1), RTSP URL, or file path', max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('resolution_width', models.IntegerField(default=640)),
                ('resolution_height', models.IntegerField(default=480)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Video Source',
                'verbose_name_plural': 'Video Sources',
            },
        ),
        migrations.CreateModel(
            name='ViolationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.ImageField(upload_to=detection.models.snapshot_upload_path)),
                ('zoomed_snapshot', models.ImageField(blank=True, null=True, upload_to=detection.models.snapshot_upload_path)),
                ('detection_data', models.TextField(help_text='JSON string of detection results')),
                ('confidence', models.FloatField()),
                ('status', models.CharField(choices=[('detected', 'Initially Detected'), ('confirmed', 'Violation Confirmed'), ('false_alarm', 'False Alarm'), ('resolved', 'Resolved')], default='detected', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('video_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violation_events', to='detection.videosource')),
            ],
            options={
                'verbose_name': 'Violation Event',
                'verbose_name_plural': 'Violation Events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ROIPolygon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('points', models.TextField(help_text='JSON string of points: [[x1,y1], [x2,y2], ...]')),
                ('active', models.BooleanField(default=True)),
                ('video_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roi_polygons', to='detection.videosource')),
            ],
            options={
                'verbose_name': 'ROI Polygon',
                'verbose_name_plural': 'ROI Polygons',
            },
        ),
        migrations.CreateModel(
            name='DetectionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_threshold', models.FloatField(default=0.5)),
                ('iou_threshold', models.FloatField(default=0.45)),
                ('target_classes', models.CharField(blank=True, help_text='Comma-separated class IDs (empty for all)', max_length=255)),
                ('enable_tracking', models.BooleanField(default=True)),
                ('save_snapshots', models.BooleanField(default=True)),
                ('video_source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detection_setting', to='detection.videosource')),
            ],
        ),
    ]
