# Generated by Django 4.2.7 on 2025-10-05 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("detection", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="violationevent",
            table="violation_events",
        ),
    ]
